name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['**/*']
  push:
    branches:
      - master
    paths: ['**/*']

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v1

      - name: Build
        id: build
        run: |
          cmake CMakeLists.txt
          make

      - name: Tests
        id: tests
        run: |
          ./tests.sh
